void EEZS_GENPT_0006_0025_MuOverBins()
{
//=========Macro generated from canvas: c/c
//=========  (Sat Feb 10 01:49:07 2024) by ROOT version 6.12/07
   TCanvas *c = new TCanvas("c", "c",1,1,887,685);
   gStyle->SetOptStat(0);
   c->SetHighLightColor(2);
   c->Range(0,0,1,1);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetGridx();
   c->SetGridy();
   c->SetLeftMargin(0.14);
   c->SetRightMargin(0.04);
   c->SetTopMargin(0.13);
   c->SetBottomMargin(0.14);
   c->SetFrameBorderMode(0);
   
   TH1F *__4 = new TH1F("__4","",1,6,25);
   __4->SetMinimum(0.6);
   __4->SetMaximum(1.2);
   __4->SetDirectory(0);
   __4->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   __4->SetLineColor(ci);
   __4->GetXaxis()->SetTitle("p_{t, gen} [GeV]");
   __4->GetXaxis()->SetNdivisions(505);
   __4->GetXaxis()->SetLabelFont(42);
   __4->GetXaxis()->SetLabelSize(0.05);
   __4->GetXaxis()->SetTitleSize(0.06);
   __4->GetXaxis()->SetTitleFont(42);
   __4->GetYaxis()->SetTitle("#mu");
   __4->GetYaxis()->SetLabelFont(42);
   __4->GetYaxis()->SetLabelSize(0.05);
   __4->GetYaxis()->SetTitleSize(0.06);
   __4->GetYaxis()->SetTitleOffset(1.1);
   __4->GetYaxis()->SetTitleFont(42);
   __4->GetZaxis()->SetLabelFont(42);
   __4->GetZaxis()->SetLabelSize(0.035);
   __4->GetZaxis()->SetTitleSize(0.035);
   __4->GetZaxis()->SetTitleFont(42);
   __4->Draw("");
   Double_t xAxis1[2] = {6, 25}; 
   
   TH1F *mu_rawformula_clone__5 = new TH1F("mu_rawformula_clone__5","",1, xAxis1);
   mu_rawformula_clone__5->SetBinContent(1,0.8142803);
   mu_rawformula_clone__5->SetBinError(1,0.004896988);
   mu_rawformula_clone__5->SetEntries(1);
   mu_rawformula_clone__5->SetStats(0);

   ci = 1179;
   color = new TColor(ci, 1, 0, 0, " ", 0.3);
   mu_rawformula_clone__5->SetFillColor(ci);
   mu_rawformula_clone__5->SetLineColor(2);
   mu_rawformula_clone__5->SetLineWidth(2);
   mu_rawformula_clone__5->SetMarkerSize(0);
   mu_rawformula_clone__5->GetXaxis()->SetLabelFont(42);
   mu_rawformula_clone__5->GetXaxis()->SetLabelSize(0.035);
   mu_rawformula_clone__5->GetXaxis()->SetTitleSize(0.035);
   mu_rawformula_clone__5->GetXaxis()->SetTitleFont(42);
   mu_rawformula_clone__5->GetYaxis()->SetLabelFont(42);
   mu_rawformula_clone__5->GetYaxis()->SetLabelSize(0.035);
   mu_rawformula_clone__5->GetYaxis()->SetTitleSize(0.035);
   mu_rawformula_clone__5->GetYaxis()->SetTitleOffset(0);
   mu_rawformula_clone__5->GetYaxis()->SetTitleFont(42);
   mu_rawformula_clone__5->GetZaxis()->SetLabelFont(42);
   mu_rawformula_clone__5->GetZaxis()->SetLabelSize(0.035);
   mu_rawformula_clone__5->GetZaxis()->SetTitleSize(0.035);
   mu_rawformula_clone__5->GetZaxis()->SetTitleFont(42);
   mu_rawformula_clone__5->Draw("SAMEE2");
   Double_t xAxis2[2] = {6, 25}; 
   
   TH1F *mu_rawformula__6 = new TH1F("mu_rawformula__6","",1, xAxis2);
   mu_rawformula__6->SetBinContent(1,0.8142803);
   mu_rawformula__6->SetBinError(1,0.004896988);
   mu_rawformula__6->SetEntries(1);
   mu_rawformula__6->SetStats(0);
   mu_rawformula__6->SetLineColor(2);
   mu_rawformula__6->SetLineWidth(2);
   mu_rawformula__6->SetMarkerSize(0);
   mu_rawformula__6->GetXaxis()->SetLabelFont(42);
   mu_rawformula__6->GetXaxis()->SetLabelSize(0.035);
   mu_rawformula__6->GetXaxis()->SetTitleSize(0.035);
   mu_rawformula__6->GetXaxis()->SetTitleFont(42);
   mu_rawformula__6->GetYaxis()->SetLabelFont(42);
   mu_rawformula__6->GetYaxis()->SetLabelSize(0.035);
   mu_rawformula__6->GetYaxis()->SetTitleSize(0.035);
   mu_rawformula__6->GetYaxis()->SetTitleOffset(0);
   mu_rawformula__6->GetYaxis()->SetTitleFont(42);
   mu_rawformula__6->GetZaxis()->SetLabelFont(42);
   mu_rawformula__6->GetZaxis()->SetLabelSize(0.035);
   mu_rawformula__6->GetZaxis()->SetTitleSize(0.035);
   mu_rawformula__6->GetZaxis()->SetTitleFont(42);
   mu_rawformula__6->Draw("HISTSAMEE");
   Double_t xAxis3[2] = {6, 25}; 
   
   TH1F *mu_ecor74formula_clone__7 = new TH1F("mu_ecor74formula_clone__7","",1, xAxis3);
   mu_ecor74formula_clone__7->SetBinContent(1,1.02);
   mu_ecor74formula_clone__7->SetBinError(1,0.009135189);
   mu_ecor74formula_clone__7->SetEntries(1);
   mu_ecor74formula_clone__7->SetStats(0);

   ci = 1180;
   color = new TColor(ci, 0, 1, 0, " ", 0.3);
   mu_ecor74formula_clone__7->SetFillColor(ci);
   mu_ecor74formula_clone__7->SetLineColor(3);
   mu_ecor74formula_clone__7->SetLineWidth(2);
   mu_ecor74formula_clone__7->SetMarkerSize(0);
   mu_ecor74formula_clone__7->GetXaxis()->SetLabelFont(42);
   mu_ecor74formula_clone__7->GetXaxis()->SetLabelSize(0.035);
   mu_ecor74formula_clone__7->GetXaxis()->SetTitleSize(0.035);
   mu_ecor74formula_clone__7->GetXaxis()->SetTitleFont(42);
   mu_ecor74formula_clone__7->GetYaxis()->SetLabelFont(42);
   mu_ecor74formula_clone__7->GetYaxis()->SetLabelSize(0.035);
   mu_ecor74formula_clone__7->GetYaxis()->SetTitleSize(0.035);
   mu_ecor74formula_clone__7->GetYaxis()->SetTitleOffset(0);
   mu_ecor74formula_clone__7->GetYaxis()->SetTitleFont(42);
   mu_ecor74formula_clone__7->GetZaxis()->SetLabelFont(42);
   mu_ecor74formula_clone__7->GetZaxis()->SetLabelSize(0.035);
   mu_ecor74formula_clone__7->GetZaxis()->SetTitleSize(0.035);
   mu_ecor74formula_clone__7->GetZaxis()->SetTitleFont(42);
   mu_ecor74formula_clone__7->Draw("SAMEE2");
   Double_t xAxis4[2] = {6, 25}; 
   
   TH1F *mu_ecor74formula__8 = new TH1F("mu_ecor74formula__8","",1, xAxis4);
   mu_ecor74formula__8->SetBinContent(1,1.02);
   mu_ecor74formula__8->SetBinError(1,0.009135189);
   mu_ecor74formula__8->SetEntries(1);
   mu_ecor74formula__8->SetStats(0);
   mu_ecor74formula__8->SetLineColor(3);
   mu_ecor74formula__8->SetLineWidth(2);
   mu_ecor74formula__8->SetMarkerSize(0);
   mu_ecor74formula__8->GetXaxis()->SetLabelFont(42);
   mu_ecor74formula__8->GetXaxis()->SetLabelSize(0.035);
   mu_ecor74formula__8->GetXaxis()->SetTitleSize(0.035);
   mu_ecor74formula__8->GetXaxis()->SetTitleFont(42);
   mu_ecor74formula__8->GetYaxis()->SetLabelFont(42);
   mu_ecor74formula__8->GetYaxis()->SetLabelSize(0.035);
   mu_ecor74formula__8->GetYaxis()->SetTitleSize(0.035);
   mu_ecor74formula__8->GetYaxis()->SetTitleOffset(0);
   mu_ecor74formula__8->GetYaxis()->SetTitleFont(42);
   mu_ecor74formula__8->GetZaxis()->SetLabelFont(42);
   mu_ecor74formula__8->GetZaxis()->SetLabelSize(0.035);
   mu_ecor74formula__8->GetZaxis()->SetTitleSize(0.035);
   mu_ecor74formula__8->GetZaxis()->SetTitleFont(42);
   mu_ecor74formula__8->Draw("HISTSAMEE");
   Double_t xAxis5[2] = {6, 25}; 
   
   TH1F *mu_ecor91formula_clone__9 = new TH1F("mu_ecor91formula_clone__9","",1, xAxis5);
   mu_ecor91formula_clone__9->SetBinContent(1,1.022006);
   mu_ecor91formula_clone__9->SetBinError(1,0.005436383);
   mu_ecor91formula_clone__9->SetEntries(1);
   mu_ecor91formula_clone__9->SetStats(0);

   ci = 1181;
   color = new TColor(ci, 0, 0, 1, " ", 0.3);
   mu_ecor91formula_clone__9->SetFillColor(ci);
   mu_ecor91formula_clone__9->SetLineColor(4);
   mu_ecor91formula_clone__9->SetLineWidth(2);
   mu_ecor91formula_clone__9->SetMarkerSize(0);
   mu_ecor91formula_clone__9->GetXaxis()->SetLabelFont(42);
   mu_ecor91formula_clone__9->GetXaxis()->SetLabelSize(0.035);
   mu_ecor91formula_clone__9->GetXaxis()->SetTitleSize(0.035);
   mu_ecor91formula_clone__9->GetXaxis()->SetTitleFont(42);
   mu_ecor91formula_clone__9->GetYaxis()->SetLabelFont(42);
   mu_ecor91formula_clone__9->GetYaxis()->SetLabelSize(0.035);
   mu_ecor91formula_clone__9->GetYaxis()->SetTitleSize(0.035);
   mu_ecor91formula_clone__9->GetYaxis()->SetTitleOffset(0);
   mu_ecor91formula_clone__9->GetYaxis()->SetTitleFont(42);
   mu_ecor91formula_clone__9->GetZaxis()->SetLabelFont(42);
   mu_ecor91formula_clone__9->GetZaxis()->SetLabelSize(0.035);
   mu_ecor91formula_clone__9->GetZaxis()->SetTitleSize(0.035);
   mu_ecor91formula_clone__9->GetZaxis()->SetTitleFont(42);
   mu_ecor91formula_clone__9->Draw("SAMEE2");
   Double_t xAxis6[2] = {6, 25}; 
   
   TH1F *mu_ecor91formula__10 = new TH1F("mu_ecor91formula__10","",1, xAxis6);
   mu_ecor91formula__10->SetBinContent(1,1.022006);
   mu_ecor91formula__10->SetBinError(1,0.005436383);
   mu_ecor91formula__10->SetEntries(1);
   mu_ecor91formula__10->SetStats(0);
   mu_ecor91formula__10->SetLineColor(4);
   mu_ecor91formula__10->SetLineWidth(2);
   mu_ecor91formula__10->SetMarkerSize(0);
   mu_ecor91formula__10->GetXaxis()->SetLabelFont(42);
   mu_ecor91formula__10->GetXaxis()->SetLabelSize(0.035);
   mu_ecor91formula__10->GetXaxis()->SetTitleSize(0.035);
   mu_ecor91formula__10->GetXaxis()->SetTitleFont(42);
   mu_ecor91formula__10->GetYaxis()->SetLabelFont(42);
   mu_ecor91formula__10->GetYaxis()->SetLabelSize(0.035);
   mu_ecor91formula__10->GetYaxis()->SetTitleSize(0.035);
   mu_ecor91formula__10->GetYaxis()->SetTitleOffset(0);
   mu_ecor91formula__10->GetYaxis()->SetTitleFont(42);
   mu_ecor91formula__10->GetZaxis()->SetLabelFont(42);
   mu_ecor91formula__10->GetZaxis()->SetLabelSize(0.035);
   mu_ecor91formula__10->GetZaxis()->SetTitleSize(0.035);
   mu_ecor91formula__10->GetZaxis()->SetTitleFont(42);
   mu_ecor91formula__10->Draw("HISTSAMEE");
   
   TLegend *leg = new TLegend(0,0,0,0,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("mu_rawformula","#mu_{Gaus, raw}  ","lf");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("mu_ecor74formula","#mu_{Gaus, corr. (current)}  ","lf");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("mu_ecor91formula","#mu_{Gaus, corr. (new)}  ","lf");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
